swagger: '2.0'
info:
  version: '0.1.0'
  title: gamification API
  description: An API to gamify application
host: localhost:8080
basePath: /api
schemes:
- http
paths:
  /users:
    get:
      description: retrieve badge and pointscale of a user
      operationId: getUser
      produces:
      - application/json
      parameters:
      - name: apiToken
        in: query
        required: true
        type: string
      - name: userName
        in: query
        required: true
        type: string
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /events:
    post:
      description: generate an event
      operationId: generateEvent
      consumes:
      - application/json
      parameters:
      - name: event
        in: body
        required: true
        schema:
          $ref: '#/definitions/Event'
      responses:
        '201':
          description: success
          schema:
            type: string
  /badges:
    post:
      description: create a badge
      operationId: createBadge
      consumes:
      - application/json
      parameters:
      - name: badge
        in: body
        required: true
        schema:
          $ref: '#/definitions/Badge'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of badges of an application
      operationId: getBadges
      produces:
      - application/json
      parameters:
      - name: apiToken
        in: query
        required: true
        type: string
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Badge'
    put:
      description: update a badge
      operationId: updateBadge
      consumes:
      - application/json
      parameters:
      - name: Updatebadge
        in: body
        required: true
        schema:
          $ref: '#/definitions/UpdateBadge'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Badge'
    delete:
      description: delete a badge
      operationId: deleteBadge
      produces:
      - application/json
      parameters:
      - name: badge
        in: body
        required: true
        schema:
          $ref: '#/definitions/Badge'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Badge'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /PointScales:
    post:
      description: create a pointScale
      operationId: createPointScale
      consumes:
      - application/json
      parameters:
      - name: pointScale
        in: body
        required: true
        schema:
          $ref: '#/definitions/PointScale'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the pointScales of an application
      operationId: getPointScales
      produces:
      - application/json
      parameters:
      - name: apiToken
        in: query
        required: true
        type: string
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/PointScale'
    put:
      description: update a pointScale
      operationId: updatePointScale
      consumes:
      - application/json
      parameters:
      - name: updatePointScale
        in: body
        required: true
        schema:
          $ref: '#/definitions/UpdatePointScale'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PointScale'
    delete:
      description: delete a pointScale
      operationId: deletePointScale
      produces:
      - application/json
      parameters:
      - name: pointScale
        in: body
        required: true
        schema:
          $ref: '#/definitions/PointScale'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/PointScale'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /rules:
    post:
      description: create a rule
      operationId: createRule
      consumes:
      - application/json
      parameters:
      - name: rule
        in: body
        required: true
        schema:
          $ref: '#/definitions/Rule'
      responses:
        '201':
          description: created
          schema:
            type: object
    get:
      description: get the list of all rules
      operationId: getRules
      produces:
      - application/json
      parameters:
      - name: apiToken
        in: query
        required: true
        type: string
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Rule'
    put:
      description: update a rule
      operationId: updateRule
      consumes:
      - application/json
      parameters:
      - name: updateRule
        in: body
        required: true
        schema:
          $ref: '#/definitions/UpdateRule'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Rule'
    delete:
      description: delete a rule
      operationId: deleteRule
      produces:
      - application/json
      parameters:
      - name: rule
        in: body
        required: true
        schema:
          $ref: '#/definitions/RuleInfos'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/RuleInfos'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  User:
    type: object
    properties:
      apiToken:
        type: string
      name:
        type: string
      badges:
        type: array
        items:
          $ref: '#/definitions/Badge'
      pointScales:
        type: array
        items:
          $ref: '#/definitions/PointScale'
      userPointScale:
        type: array
        items:
          $ref: '#/definitions/UserPointScale'
      userEventCount:
        type: array
        items:
          $ref: '#/definitions/UserEventCount'

  Event:
    type: object
    properties:
      timestamp:
        description: 'date of the event'
        example: 2018-12-25T24:00
        format: date-time
        type: string
      apiToken:
        type: string
      userId:
        type: string
      name:
        type: string
      properties:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            value:
              type: integer
          required:
          - name
          - value
    required:
    - token
    - idUser
    - eventName

  Badge:
    type: object
    properties:
      apiToken:
        type: string
      name:
        type: string
    required:
    - apiToken
    - name

  UpdateBadge:
    type: object
    properties:
      newBadge:
        $ref: '#/definitions/Badge'
      oldName:
        type: string
    required:
    - newBadge
    - oldName

  PointScale:
    type: object
    properties:
      apiToken:
        type: string
      name:
        type: string
    required:
    - apiToken
    - name
    - value

  UpdatePointScale:
    type: object
    properties:
      newPointScale:
        $ref: '#/definitions/PointScale'
      oldName:
        type: string
    required:
    - newPointScale
    - oldName

  Rule:
    type: object
    properties:
      apiToken:
        type: string
      ruleName:
        type: string
      eventName:
        type: string
      awards:
        type: object
        properties:
          badge:
            type: array
            items:
              type: string
          point:
            type: array
            items:
              type: string
          amountofPoint:
            type: array
            items:
              type: integer
      properties:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            type:
              type: string
            compareOperator:
              type: string
            value:
              type: integer
          required:
          - type
          - compareOperator
          - value
    required:
    - apiToken
    - awards
    - properties
    - name

  UpdateRule:
    type: object
    properties:
      newRule:
        $ref: '#/definitions/Rule'
      oldName:
        type: string
    required:
    - newRule
    - oldName

  AppInfos:
    type: object
    properties:
      apiToken:
        type: string
    required:
    - apiToken

  UserInfos:
    type: object
    properties:
      apiToken:
        type: string
      name:
        type: string
    required:
    - apiToken
    - userId

  RuleInfos:
    type: object
    properties:
      apiToken:
        type: string
      name:
        type: string
    required:
    - apiToken
    - rulename

  LinkTableId:
    type: object
    properties:
      apiToken:
        type: string
      table1Id:
        type: string
      table2Id:
        type: string


  UserPointScale:
    type: object
    properties:
      linkTableId:
        $ref: '#/definitions/LinkTableId'
      value:
        type: integer


  UserEventCount:
    type: object
    properties:
      linkTableId:
        $ref: '#/definitions/LinkTableId'
      value:
        type: integer